### ISSUE TITLE
[ERROR] TypeError: Cannot read property 'image' of null

### ISSUE THREAD

**Issue by Ryz0nd** [balloonspace/balloonspace-client#23]
yarn build 후 yarn export 할 때 에러 

yarn dev했을 때는 에러가 나지 않음.

ProfileCard에서 문제가 생긴듯 함.
```
2:41:23 PM: TypeError: Cannot read property 'image' of null
2:41:23 PM:     at ProfileCard (/opt/build/repo/src/.next/server/static/GLEekkDAbswAlf9uPkVN6/pages/user.js:190:13)
2:41:23 PM:     at c (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:500)
2:41:23 PM:     at Ua (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
2:41:23 PM:     at a.render (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:45:48)
2:41:23 PM:     at a.read (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:161)
2:41:23 PM:     at renderToString (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:55:83)
2:41:23 PM:     at render (/opt/build/repo/node_modules/next-server/dist/server/render.js:79:16)
2:41:23 PM:     at renderPage (/opt/build/repo/node_modules/next-server/dist/server/render.js:255:20)
2:41:23 PM:     at Function.getInitialProps (/opt/build/repo/src/.next/server/static/GLEekkDAbswAlf9uPkVN6/pages/_document.js:208:18)
2:41:23 PM:     at Object.loadGetInitialProps (/opt/build/repo/node_modules/next-server/dist/lib/utils.js:50:35)
```

**Comment by Ryz0nd** [comment]
Used 'me &&' to null check.
